title: Dante's blog
baseline: Writing about stuff around
description: 'Come and read my blog, this is the best content ever!!!1'
baseurl: /
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
